-- 006: Female-founder investor register (venture side of investor_mandates)
-- Extends the mandate register beyond the M&A asset classes to venture investors,
-- and imports the Female Investors UK register (39 records, verified Jul 2026).
-- Advisor-only RLS from migration 003 applies unchanged: founders never read this table.

-- Widen the type constraint to cover venture-side investors.
alter table public.investor_mandates drop constraint if exists investor_mandates_investor_type_check;
alter table public.investor_mandates add constraint investor_mandates_investor_type_check
  check (investor_type in ('pe_buyout','growth_equity','family_office','strategic','angel','debt',
                           'vc','angel_syndicate','accelerator','corporate_venturing','government','other'));

-- Venture-side fields.
alter table public.investor_mandates
  add column if not exists register            text,
  add column if not exists stage_preseed_seed  boolean not null default false,
  add column if not exists stage_series_a      boolean not null default false,
  add column if not exists stage_series_b      boolean not null default false,
  add column if not exists target_cheque       text,
  add column if not exists female_founder_focus text,
  add column if not exists female_founder_mandate text,
  add column if not exists pitch_route         text,
  add column if not exists apply_url           text,
  add column if not exists website             text,
  add column if not exists contact_email       text,
  add column if not exists linkedin_url        text,
  add column if not exists portfolio_notable   text,
  add column if not exists fund_size           text,
  add column if not exists year_founded        text,
  add column if not exists office_address      text,
  add column if not exists phone               text,
  add column if not exists key_people          text,
  add column if not exists verification_status text not null default 'active'
    check (verification_status in ('active','verify_before_approach')),
  add column if not exists last_verified       text;

-- Re-runs must not duplicate the register.
create unique index if not exists investor_mandates_org_register_idx
  on public.investor_mandates (org_name, register);

insert into public.investor_mandates
  (org_name, investor_type, register, verification_status, stage_preseed_seed, stage_series_a, stage_series_b,
   target_cheque, sectors, geographies, must_haves, website, pitch_route, apply_url, contact_email, linkedin_url,
   portfolio_notable, fund_size, year_founded, office_address, phone, last_verified,
   female_founder_focus, key_people, female_founder_mandate, status)
values
  ('3 Sisters Ventures (3SV)', 'vc', 'female_investors_uk', 'verify_before_approach', true, true, false, 'Not stated publicly', '{"HealthTech & MedTech","FinTech","HR & Future of Work"}', '{"UK"}', 'Female-founded or co-founded businesses; tech-enabled solutions for women''s underserved needs', 'https://www.3sv.co.uk', 'Apply online', 'https://www.3sv.co.uk/home#Connect', 'info@3sv.co.uk', 'https://uk.linkedin.com/company/3sv-collective', 'Financielle, The Lowdown, Kanjo, Unfabled, GrandNanny', null, '2022', '3 Pancras Square, King''s Cross, London, N1C 4AG', null, 'Q2 2026', 'Yes', 'Dalia Aga-Shaw (Managing/Founding Partner); Lois Day (Partner) - per SuperScout profile', 'Backs female-founded/co-founded, tech-enabled solutions addressing women''s underserved needs - ''historically underfunded problems for women'' across Health & Self, Work & Wealth, Family & Crew verticals', 'active'),
  ('Ada Ventures', 'vc', 'female_investors_uk', 'active', true, false, false, '£250,000 to £1,000,000', '{"CleanTech & Energy","HealthTech & MedTech","FinTech","Impact & Social","General / All Sectors"}', '{"UK & Europe"}', 'UK-based tech companies; diverse and underrepresented founders; post-product, pre-revenue stage; climate equity, economic empowerment, healthy ageing themes', 'https://www.adaventures.com', 'Apply online', 'https://www.adaventures.com/apply', 'operations@adaventures.com (listed on site for partnership enquiries)', 'https://uk.linkedin.com/company/ada-ventures', 'BlakBear, Juno Bio, Greenworkx, Materials Nexus, Mirthy (exited)', '£63m (Fund II, final close March 2024)', '2018', 'London, UK', null, 'Q2 2026', 'Yes', 'Check Warner (Founding Partner); Matt Penneycard (Founding Partner); Michael Tefula (Principal & Head of Product)', '''Inclusive alpha'' thesis - assesses founders ''on their qualities, not CV, past work experience, or gut feel''; backs diverse/underrepresented founders incl. women (not exclusively female-founded); publishes Women in UK VC report', 'active'),
  ('Angel Academe', 'angel_syndicate', 'female_investors_uk', 'active', true, true, false, '£250k - £5m', '{"AI & Machine Learning","SaaS & Enterprise Software","HealthTech & MedTech","FinTech"}', '{"UK"}', 'Female-founded/co-founded tech startups; min 20% equity held by woman; UK business eligible for EIS/SEIS', 'https://www.angelacademe.com', 'Apply online', 'https://www.angelacademe.com/apply-to-pitch', null, 'https://www.linkedin.com/company/angel-academe', 'DataWollet, Zonova', null, '2014', null, null, 'Q2 2026', 'Yes', 'Sarah Turner (Co-founder & CEO); Simon Hopkins (Co-founder & COO); Yee Mun Thum (Managing Director)', '''The UK''s First EIS Fund for female founders''; backs ''Exceptional Female Founders since 2014''; criteria: female-founded/co-founded UK tech, min 20% equity held by a woman, EIS/SEIS eligible', 'active'),
  ('Barclays Eagle Labs', 'accelerator', 'female_investors_uk', 'active', true, false, false, 'Non-equity support programmes; no direct investment (NOT an equity investor)', '{"AI & Machine Learning","FinTech","CleanTech & Energy","Cybersecurity","HealthTech & MedTech","General / All Sectors"}', '{"UK"}', 'UK-based tech startups and scaleups; various programmes by stage and sector (Black Founders, Female Founders, Scaleup, Sales Growth etc.); equity-free support and co-working.', 'https://labs.uk.barclays', 'Apply online', 'https://labs.uk.barclays/what-we-offer/our-programmes/', null, 'https://www.linkedin.com/company/barclays-eagle-labs', null, '£12M Digital Growth Grant from UK Government (2023 to 2025)', '2015', 'Multiple locations across UK', null, 'Q2 2026', 'Yes', 'Elizabeth Pirrie (CEO, AccelerateHER - delivery partner for Female Founder Accelerator)', 'Female Founder Accelerator: free 9-week programme for 100 female-identifying founders/C-suite execs of UK innovation-led businesses beyond idea stage; equity-free support (NOT an equity investor)', 'active'),
  ('Cornerstone Partners', 'angel_syndicate', 'female_investors_uk', 'active', true, true, false, '£250k to £1m initial (Cornerstone VC fund, follow-on reserved)', '{"General / All Sectors"}', '{"UK"}', 'Angel investor network backing UK pre-seed and seed-stage businesses owned and run by black and diverse founders. Looks for founders with inherent or acquired diversity building high-growth, tech-led businesses that can scale into large sustainable companies.', 'https://cornerstonepartners.co.uk', 'Apply online', 'https://cornerstonepartners.co.uk/pitch/', null, 'https://www.linkedin.com/company/cornerstonepartners', 'Nudea, Slinger, Coordinate Sport', null, null, null, null, 'Q2 2026', 'Yes', 'Rodney Appiah (Co-founder; one of six co-founders)', 'Angel network investing in ''pre seed and seed stage businesses across the UK led by black and diverse founders'' (SEIS/EIS); diversity mandate includes gender (''inherent or acquired diversity'')', 'active'),
  ('Cornerstone VC', 'vc', 'female_investors_uk', 'active', true, false, false, '£250k to £1M first cheque; 40% reserved for follow-on', '{"AI & Machine Learning","SaaS & Enterprise Software","FinTech","HealthTech & MedTech","General / All Sectors"}', '{"UK"}', 'UK tech-enabled companies at pre-seed and seed; ''people first'' strategy; explicit focus on diverse founders (ethnicity, gender, age, geography); aims for 30% of deal flow from outside London.', 'https://www.cornerstonevc.co', 'Apply online', 'https://www.cornerstonevc.co/apply', 'hello@cornerstonevc.co', 'https://www.linkedin.com/company/cornerstonevc', 'Evaro, Smart Bricks, Not publicly listed (portfolio in stealth)', '£20M (Fund I)', '2022', '14 New Street, London, EC2M 4HE', null, 'Q2 2026', 'Yes', 'Rodney Appiah (Founder & Managing Partner)', '''People first'' fund placing ''greater emphasis on team diversity'' (ethnicity, gender, age, geography); 20m GBP Fund I backing diverse teams at pre-seed/seed', 'active'),
  ('Helen Chang', 'angel', 'female_investors_uk', 'active', true, true, false, 'Not stated publicly', '{"Impact & Social","FinTech","SaaS & Enterprise Software","HealthTech & MedTech","General / All Sectors"}', '{"UK"}', 'Sustainability, female-founded, tech-enabled focus', 'https://uk.linkedin.com/in/helenchang', 'Warm introduction', null, null, 'https://uk.linkedin.com/in/helenchang', null, null, '2015', 'London, UK', null, 'Q2 2026', 'Yes', 'Helen Chang (individual angel investor)', 'Female-founded, sustainability and tech-enabled focus (per directory listing only; no public mandate statement found)', 'active'),
  ('HERmesa', 'angel_syndicate', 'female_investors_uk', 'active', true, false, false, '£50k to £150k', '{"General / All Sectors"}', '{"UK"}', 'Female-founded start-ups only', 'https://www.hermesa.co.uk', 'Apply online', 'https://airtable.com/appUOjZecCsh1muEt/shrs6fTceS6ON8nCB', 'hello@hermesa.co.uk', 'https://www.linkedin.com/company/hermesa', null, null, '2020', null, null, 'Q2 2026', 'Yes', 'Marla Shapiro (Founder & CEO)', '''We are proud to support a growing portfolio of exceptional women-led start-ups''; angel syndicate of operators-turned-angels investing in female (co)founded companies; partnership with Science Angel Syndicate for female-(co)founded science companies', 'active'),
  ('Impact X Capital Partners', 'vc', 'female_investors_uk', 'active', true, true, false, 'Not stated publicly', '{"AI & Machine Learning","HealthTech & MedTech","FinTech","Media & Publishing","Impact & Social"}', '{"UK & Europe"}', 'Underrepresented founders; Afro-Caribbean diaspora and diverse entrepreneurs; tech and creative media; UK and Europe', 'https://impactxcapital.com', 'Apply online', 'https://ai.impactxcapital.com/pitch.php', null, 'https://uk.linkedin.com/company/impact-x-capital-partners-llp', 'Marshmallow, Salvo Health, Afrocenchix', null, '2018', null, null, 'Q2 2026', 'Yes', 'Eric Collins (Founder & CEO); Paula Groves (Founding Partner); Ursula Burns, Ric Lewis, Lenny Henry (founding members)', 'Invests in ''underrepresented entrepreneurs from across Europe'' with particular emphasis on people of colour and women; pitch form explicitly asks for number of female staff', 'active'),
  ('Investing Women Angels', 'angel_syndicate', 'female_investors_uk', 'active', true, true, false, '£50,000 to £1,500,000', '{"General / All Sectors"}', '{"UK - Scotland"}', 'Female-founded or co-founded businesses; founding team (not individual)', 'https://www.investingwomen.co.uk', 'Apply online', 'https://www.investingwomen.co.uk/pitch/', null, 'https://uk.linkedin.com/company/investing-women', null, null, '2013', null, null, 'Q2 2026', 'Yes', 'Nicki Thomson-Berwick (Chief Operating Officer, active angel investor)', 'Scotland''s all-women angel syndicate focused on ''the advancement of female founded and female led businesses, through investment, community, and education''; 90% of 2.3m GBP invested (25 companies) has gone to female-founded companies; Investing in Women Code signatory', 'active'),
  ('Meri Williams', 'angel', 'female_investors_uk', 'active', true, false, false, 'Not stated publicly', '{"DeepTech","SaaS & Enterprise Software","HR & Future of Work","AI & Machine Learning"}', '{"UK"}', 'Deep tech, developer tools, HR-tech, diversity focus', 'https://uk.linkedin.com/in/meriwilliams', 'Warm introduction', null, null, 'https://uk.linkedin.com/in/meriwilliams', null, null, '2015', 'London, UK', null, 'Q2 2026', 'Yes', 'Meri Williams (CTO, Pleo; angel investor)', 'Deep tech / dev tools / HR-tech with diversity focus (per directory listings; no public mandate statement)', 'active'),
  ('Mint Ventures', 'angel_syndicate', 'female_investors_uk', 'active', true, false, false, 'From £2,000 per investor per annum', '{"Impact & Social","General / All Sectors"}', '{"UK - Scotland"}', 'Women-led or diverse teams; products/services meeting women''s needs with social, ethical or environmental purpose', 'https://www.mintventures.co.uk', 'Apply online', 'https://www.mintventures.co.uk/entrepreneurs/', 'info@mintventures.co.uk', 'https://uk.linkedin.com/company/mint-ventures', 'Transparently, Heero Technologies, Freja Bone Broth, Inicio AI', null, null, null, null, 'Q2 2026', 'Yes', 'Gillian Fleming (Co-founder & CEO)', '''We understand the power of women on entrepreneurial teams and use it as an advantage in selecting investment opportunities''; backs women-led/diverse teams and products meeting women''s needs with social/ethical/environmental purpose; Investing in Women Code signatory', 'active'),
  ('Morgan Stanley Inclusive & Sustainable Ventures', 'accelerator', 'female_investors_uk', 'active', true, false, false, '£250,000 per company', '{"Impact & Social","CleanTech & Energy","HealthTech & MedTech","EdTech"}', '{"UK & Europe"}', 'Pre-seed to Series A; underrepresented founders; applications due March 31 2026', 'https://www.morganstanley.com/about-us/inclusive-sustainable-ventures', 'Apply online', 'https://www.morganstanley.com/about-us/inclusive-sustainable-ventures', null, null, 'Cytochroma, Danu Robotics, Envisionit Deep AI, Mimicrete, Tuli Health', null, '2017', null, null, 'Q2 2026', 'Yes', 'Sanghamitra Karra (Global Co-Head); LaToya Wilson (Global Co-Head)', 'Supports ''early-stage startups and nonprofits that are building solutions for a more inclusive and sustainable future'' (evolution of the Inclusive Ventures Lab, which targeted underrepresented founders incl. women)', 'active'),
  ('Rising Tide Europe', 'angel_syndicate', 'female_investors_uk', 'verify_before_approach', true, false, false, 'Pooled fund of €1m+ invested across 6 to 10 early-stage companies per programme', '{"General / All Sectors","Impact & Social","FinTech","HealthTech & MedTech"}', '{"UK & Europe"}', 'Female-led ventures; works with local angel networks', 'https://www.risingtide.eu', 'Contact page', 'https://www.risingtide.vc/', null, 'https://www.linkedin.com/company/rising-tide-eu/', null, null, null, null, null, 'Q2 2026', 'Yes', 'Candace Johnson (Co-founder, per 2017 EU-Startups interview); programme delivered with Go Beyond Investing network', 'Cohorts of women angel investors from four continents pooling capital to invest in female-led European ventures (''Rising Tide'' programmes RTE1-4)', 'active'),
  ('Sara Davies MBE investment vehicle', 'family_office', 'female_investors_uk', 'active', true, true, false, '£25K to £75K typical', '{"DTC & Consumer Brands","Retail & E-commerce","HealthTech & MedTech","EdTech","Fashion & Lifestyle","Sports & Entertainment","Food & Drink"}', '{"UK & Ireland"}', 'Female-founder friendly; consumer/lifestyle with clear scalability', 'https://sara-davies.com', 'Contact page', 'https://sara-davies.com/business/', 'press@sara-davies.com (press only)', 'https://uk.linkedin.com/in/sara-davies-mbe-7406854', 'Apraceswimming (Mar 2025), Mystery Jersey King (Jan 2025), SKIN (Mar 2024), Sibstar, Mini First Aid, My Expert Midwife', null, '2005', 'Crafter''s Companion HQ, Coundon, County Durham', null, 'Q2 2026', 'Yes', 'Sara Davies MBE (investor; founder, Crafter''s Companion); team incl. an Investment Director and EA reachable via site contact form', 'Female-founder-friendly consumer/lifestyle investor; no formal published mandate (''drawn to organisations with real purpose, heart and drive'')', 'active'),
  ('Scott Mackin', 'angel', 'female_investors_uk', 'active', true, false, false, 'Not stated publicly', '{"CleanTech & Energy","Impact & Social","HealthTech & MedTech"}', '{"UK"}', 'Women-led startups; sustainability focus', 'https://uk.linkedin.com/in/scott-mackin', 'Warm introduction', null, null, 'https://uk.linkedin.com/in/scott-mackin', 'The Shellworks, Baobab Circle, Not available, Not available, Not available', null, '2018', 'London, UK', null, 'Q2 2026', 'Yes', 'Scott Mackin (Managing Partner, Denham Capital; angel investor)', '''Actively engages in angel investing... with a strong focus on supporting female founders'' plus energy transition/sustainability (per Tech Funding News profile)', 'active'),
  ('Simsan Ventures', 'vc', 'female_investors_uk', 'active', true, false, false, 'Not stated publicly', '{"DeepTech"}', '{"UK"}', 'Early-stage diversity VC fund backing underrepresented founders and diverse teams building frontier technologies. Prioritises Deep Tech and Fintech from pre-seed to Series A, and supports cross-border innovation between Europe and Asia (South Korea and India).', 'https://simsan.vc', 'Apply online', 'https://simsan.vc/pitch/', null, 'https://www.linkedin.com/company/simsan-ventures', null, null, '2021', '83 Baker Street, London, W1U 6AG', null, 'Q2 2026', 'Yes', 'Sahil Chopra (Co-founder & General Partner); Sagar Chopra (Co-founder & General Partner); Rancho Lee (APAC Partner)', '''Committed to democratizing venture capital by investing in diverse teams and underrepresented founders'' - actively seeks founders identifying as women, ethnic minorities, immigrants and LGBTQIA+; deep tech/fintech, UK-Europe-India-South Korea', 'active'),
  ('SyndicateRoom', 'vc', 'female_investors_uk', 'active', true, true, false, '£400k to £5m', '{"General / All Sectors"}', '{"UK"}', 'Data-driven EIS fund (Access EIS) that does not take direct pitches: it co-invests automatically alongside the UK best-performing business angels, building diversified portfolios of 30-plus EIS-qualifying early-stage startups. Sister funds run with Angel Academe (female-founded tech) and Carbon13 (climate, SEIS).', 'https://www.syndicateroom.com', 'Email pitch', 'https://www.syndicateroom.com/raise', 'contactus@syndicateroom.com', 'https://www.linkedin.com/company/syndicate-room', 'Tred, SPOKE, Grubby', null, '2013', 'Wellington House, East Road, Cambridge, CB1 1BH', '01223 478 558', 'Q2 2026', 'Yes', 'Graham Schwikkard (CEO); Tom Britton (Co-founder); Francesca O''Brien (Partner, Risk)', 'Runs Angel Academe EIS fund - ''the UK''s first EIS fund focused on female founded businesses'' (min investor ticket 10k GBP; next deadline 30 Oct 2026); flagship Access EIS fund is not FF-specific (co-invests with top-performing angels)', 'active'),
  ('Two Magnolias', 'vc', 'female_investors_uk', 'active', true, true, false, '£100k to £1m', '{"CleanTech & Energy","Impact & Social"}', '{"UK"}', 'UK venture capital fund (female-led, impact focus) backing early-stage British businesses tackling sustainability and human health. Targets underrepresented founders and UK regions and devolved nations often underserved by venture capital.', 'https://www.twomagnolias.co.uk', 'Contact page', 'https://www.twomagnolias.co.uk/contact', null, 'https://uk.linkedin.com/company/two-magnolias-ltd', null, null, '2019', null, null, 'Q2 2026', 'Yes', 'Jessica Rasmussen (Co-founder); Marie Korde (Co-founder); Roxanna Ramtin (Head of Operations)', 'Female-founded/led VC ''investing in underrepresented founders in the UK who are solving the most pressing problems in the fields of Transformational Economy and Health Equity''', 'active'),
  ('Wendy Tan White', 'angel', 'female_investors_uk', 'active', true, true, false, 'Not stated publicly', '{"AI & Machine Learning","DeepTech","SaaS & Enterprise Software","HealthTech & MedTech","General / All Sectors"}', '{"UK & Europe"}', 'Deep tech, female founders, AI focus', 'https://uk.linkedin.com/in/wendytanwhite', 'Warm introduction', null, null, 'https://uk.linkedin.com/in/wendytanwhite', 'Moonfruit, Not available, Not available, Not available, Not available', null, '2010', 'London, UK', null, 'Q2 2026', 'Yes', 'Wendy Tan White MBE (CEO, Intrinsic (Alphabet); co-founder Moonfruit; angel investor)', 'Known backer of deep tech and female founders (per profiles); no published mandate', 'active'),
  ('Women Angels of the North', 'angel_syndicate', 'female_investors_uk', 'active', true, false, false, '£50k to £250k', '{"General / All Sectors"}', '{"UK - North of England only"}', 'Female founders in the North of England; innovation and creative sectors; minimum £2,000 per investor member', 'https://www.fundhernorth.com', 'Apply online', 'https://www.fundhernorth.com/entrepreneurs', null, 'https://www.linkedin.com/company/fund-her-north', null, null, null, null, null, 'Q2 2026', 'Yes', 'Jordan Dargue (Co-founder, Fund Her North); Helen Oldham (Co-founder, Fund Her North)', '''We exist to give Northern, female business leaders equal access to funding to help them successfully scale their businesses''; 40+ women across the funding ecosystem backing female-led businesses in the North of England through start-up, scale-up and exit', 'active'),
  ('Pink Salt Ventures', 'vc', 'female_investors_uk', 'active', true, false, false, 'c. £250k-£500k initial cheques', '{"Sector-agnostic","tilt to consumer","health & wellness","femtech"}', '{"UK (some Europe)"}', 'The UK''s first VC firm dedicated exclusively to female founders (invests where women hold 50%+ of founding equity)', null, 'Warm introduction', null, null, 'https://uk.linkedin.com/company/pink-salt-ventures', 'MPowder, Juno Bio, Mirza', null, '2019', 'London, UK', null, 'Jul 2026 (web research)', 'Yes', null, 'The UK''s first VC firm dedicated exclusively to female founders (invests where women hold 50%+ of founding equity)', 'active'),
  ('January Ventures', 'vc', 'female_investors_uk', 'active', true, false, false, null, '{"B2B software","digital health","climate","fintech","future of work"}', '{"US & Europe incl. UK"}', 'Invests early in overlooked founders - 80% of portfolio companies have a female founder; founded by two female GPs (formerly Jane VC)', 'https://www.january.ventures/', 'Apply online (open pitch form)', 'https://januaryventures.typeform.com/to/CBAt9iIh', null, 'https://www.linkedin.com/company/january-ventures', 'Ethena, Treefera, PlanetFWD, Oula, Guidewheel', null, null, null, null, 'Jul 2026 (web research)', 'Yes', null, 'Invests early in overlooked founders - 80% of portfolio companies have a female founder; founded by two female GPs (formerly Jane VC)', 'active'),
  ('Sie Ventures', 'vc', 'female_investors_uk', 'active', true, false, false, null, '{"AI & deeptech","fintech","femtech","healthcare","sustainability","B2B SaaS"}', '{"UK & Europe"}', 'Araya Sie Fund "backs female-led tech startups in the UK and Europe"; Sie Catalyst programme exists "to level the playing field for female founders"', 'https://www.sie.ventures/', 'Apply online', 'https://www.sie.ventures/pitch-for-investment', null, null, '250+ companies supported via Catalyst; portfolio has raised £300m+', 'Araya Sie Fund: £15m target, £7.5m first close (2026)', '2021', 'London, UK', null, 'Jul 2026 (web research)', 'Yes', null, 'Araya Sie Fund "backs female-led tech startups in the UK and Europe"; Sie Catalyst programme exists "to level the playing field for female founders"', 'active'),
  ('Voulez Capital', 'vc', 'female_investors_uk', 'active', true, true, false, null, '{"Purpose-driven businesses (sector-agnostic)"}', '{"UK & Europe"}', 'Europe''s first VC for female founders - we aim to redress this by investing in outstanding female founders', 'https://www.voulez-capital.com/', 'Contact page', 'https://www.voulez-capital.com/', null, null, null, null, '2017', 'London, UK', null, 'Jul 2026 (web research)', 'Yes', null, 'Europe''s first VC for female founders - we aim to redress this by investing in outstanding female founders', 'active'),
  ('Merian Ventures', 'vc', 'female_investors_uk', 'active', true, true, true, null, '{"Deep tech: AI","cyber","blockchain/digital networks","STEM"}', '{"US & UK"}', 'Backs female-founded, co-founded or majority women-owned deep tech companies ("women-led innovation")', 'https://www.merianventures.com/', 'Email pitch / Contact page', 'https://www.merianventures.com/contact', 'info@merianventures.com', 'https://www.linkedin.com/company/merian-ventures', null, null, '2015', 'San Francisco & London', null, 'Jul 2026 (web research)', 'Yes', null, 'Backs female-founded, co-founded or majority women-owned deep tech companies ("women-led innovation")', 'active'),
  ('Auxxo Female Catalyst Fund', 'vc', 'female_investors_uk', 'active', true, false, false, 'Co-investment cheques alongside lead investors', '{"Sector-agnostic"}', '{"Europe incl. UK"}', 'Exclusively invests in teams with at least one female founder', 'https://auxxo.de/', 'Apply online or email pitch', 'https://auxxo.de/get-funded/', 'partners@auxxo.de', 'https://www.linkedin.com/company/auxxo/', 'Emidat, inne, BioOrbit, Filu', 'Fund II: €26m first close (2025)', null, 'Berlin, Germany', null, 'Jul 2026 (web research)', 'Yes', null, 'Exclusively invests in teams with at least one female founder', 'active'),
  ('Fund F', 'vc', 'female_investors_uk', 'active', true, false, false, 'Tickets up to €600k', '{"Sector-agnostic","digital","scalable business models"}', '{"Europe-wide (companies founded/based anywhere in Europe)"}', 'Exclusively invests in teams with at least one female co-founder', 'https://www.fund-f.com/', 'Apply online (submit pitch)', 'https://www.fund-f.com/', null, null, 'SENVO, KOA', '€28m (Fund I, closed 2025)', '2022', 'Auerspergstrasse 7/21, 1080 Vienna, Austria', null, 'Jul 2026 (web research)', 'Yes', null, 'Exclusively invests in teams with at least one female co-founder', 'active'),
  ('Pact VC', 'vc', 'female_investors_uk', 'active', true, false, false, null, '{"Access (fintech","financial inclusion)","Betterment (healthtech","edtech","future of work)","Climate"}', '{"UK","US","Europe & emerging markets"}', 'Female-founded and female-led VC (three women GPs, backed by Anne Hathaway) with explicit focus on diverse/underrepresented founding teams', 'https://www.pactvc.com/', 'Apply online', 'https://airtable.com/appguDbkmDtYm4AFf/shrZUualXwAaek0kx', 'team@pactvc.com', null, 'Team-GPT, Sidekick, UnitPlus, FlapKap', '£30m Fund I', '2022', 'London, UK', null, 'Jul 2026 (web research)', 'Yes', null, 'Female-founded and female-led VC (three women GPs, backed by Anne Hathaway) with explicit focus on diverse/underrepresented founding teams', 'active'),
  ('Female Innovators Lab Fund (Barclays x Anthemis)', 'corporate_venturing', 'female_investors_uk', 'active', true, false, false, 'First institutional cheque; size varies by company', '{"Fintech / financial services"}', '{"US","Canada","UK & Europe"}', 'A venture fund and studio dedicated to investing and cultivating entrepreneurial talent in women across the financial services ecosystem', 'https://ecosystem.anthemis.com/female-innovators-lab/', 'Apply online (rolling Pitch Us form) or email', 'https://ecosystem.anthemis.com/female-innovators-lab/', 'femaleinnovatorslab@anthemis.com', null, 'Addition Wealth, Clutch Wallet, Fifth Dimension AI, Nivelo', '$50m (2023)', '2019', 'London & New York', null, 'Jul 2026 (web research)', 'Yes', null, 'A venture fund and studio dedicated to investing and cultivating entrepreneurial talent in women across the financial services ecosystem', 'active'),
  ('Invest in Women Taskforce', 'government', 'female_investors_uk', 'active', true, true, true, '£250m+ funding pool deployed via women-led and mixed investment managers', '{"Sector-agnostic"}', '{"UK"}', 'Making the UK the best place in the world for women entrepreneurs - funding pool for women-powered businesses, invested by female and mixed-gender investing teams; backed by HM Treasury and DBT', 'https://www.investinwomentaskforce.org/', 'Contact page (capital flows via partner funds)', 'https://www.investinwomentaskforce.org/', null, null, null, '£250m+ pledged; £115m+ deployed', '2024', 'London, UK', null, 'Jul 2026 (web research)', 'Yes', null, 'Making the UK the best place in the world for women entrepreneurs - funding pool for women-powered businesses, invested by female and mixed-gender investing teams; backed by HM Treasury and DBT', 'active'),
  ('Fund Her North', 'angel_syndicate', 'female_investors_uk', 'active', true, true, false, 'Facilitates angel/VC rounds; 40+ women investors with £1.2bn combined investment power', '{"Sector-agnostic"}', '{"North of England"}', 'Give Northern, female business leaders equal access to funding to help them successfully scale', 'https://www.fundhernorth.com', 'Apply online (Looking to Raise)', 'https://www.fundhernorth.com/entrepreneurs', null, 'https://www.linkedin.com/company/fund-her-north', null, null, '2020', 'Leeds / North of England', null, 'Jul 2026 (web research)', 'Yes', null, 'Give Northern, female business leaders equal access to funding to help them successfully scale', 'active'),
  ('Lifted Ventures', 'angel_syndicate', 'female_investors_uk', 'active', true, false, false, null, '{"Sector-agnostic"}', '{"North of England (Leeds & Newcastle hubs)","UK"}', 'Increase the flow of early stage capital to female founders, and promote the business benefits of backing women', 'https://liftedventures.co.uk/', 'Apply online', 'https://share-eu1.hsforms.com/1UaK10c8PQjaR1M7v9rSpUA2deivg', 'info@liftedventures.co.uk', 'https://www.linkedin.com/company/liftedventures', null, null, '2024 (registered 2023)', 'Nexus, University of Leeds, Discovery Way, Leeds LS2 3AA', null, 'Jul 2026 (web research)', 'Yes', null, 'Increase the flow of early stage capital to female founders, and promote the business benefits of backing women', 'active'),
  ('AwakenAngels (AwakenHub)', 'angel_syndicate', 'female_investors_uk', 'active', true, false, false, 'Pre-seed syndicate cheques; portfolio companies have secured £4m+', '{"Sector-agnostic","impact-led"}', '{"Island of Ireland (Northern Ireland & ROI) + diaspora"}', 'The first and only all-island of Ireland women-led investment syndicate, investing in women-led businesses', 'https://www.awakenangelshq.com/', 'Apply online', 'https://www.awakenangelshq.com/fundraising', null, null, null, null, '2022', 'Belfast / Dublin', null, 'Jul 2026 (web research)', 'Yes', null, 'The first and only all-island of Ireland women-led investment syndicate, investing in women-led businesses', 'active'),
  ('Hatch Enterprise', 'accelerator', 'female_investors_uk', 'active', true, false, false, 'Free/bursaried programmes (worth £3,000+); grant opportunities for graduates', '{"Sector-agnostic"}', '{"UK (London base)"}', 'Dedicated "support for women and other marginalised genders", incl. its Female Founders Accelerator programmes', 'https://hatchenterprise.org/', 'Apply online', 'https://hatchenterprise.org/our-programmes/', null, 'https://uk.linkedin.com/company/hatch-enterprise-uk', null, null, '2014', '53-63 East Street, Southwark, London SE17 2DJ', null, 'Jul 2026 (web research)', 'Yes', null, 'Dedicated "support for women and other marginalised genders", incl. its Female Founders Accelerator programmes', 'active'),
  ('AccelerateHER', 'accelerator', 'female_investors_uk', 'active', true, false, false, 'Non-dilutive: awards, trade missions, Ready to Raise & W2W programmes (links to sister angel group Investing Women Angels)', '{"Sector-agnostic"}', '{"Scotland / UK"}', 'Accelerate the growth, backing and visibility of high growth potential female founders in Scotland (AccelerateHER Awards; Female Founders Association)', 'https://accelerateher.co.uk/', 'Apply online', 'https://accelerateher.co.uk/', 'info@accelerateher.co.uk', null, 'Award finalists have raised £67m+', null, '2015', '2nd Floor, Elder House, Multrees Walk, Edinburgh EH1 3DX', null, 'Jul 2026 (web research)', 'Yes', null, 'Accelerate the growth, backing and visibility of high growth potential female founders in Scotland (AccelerateHER Awards; Female Founders Association)', 'active'),
  ('Scottish EDGE (incl. Pathways EDGE)', 'government', 'female_investors_uk', 'active', true, false, false, 'Grant & loan awards up to c. £100k', '{"Sector-agnostic (incl. social enterprise","creative","circular economy)"}', '{"Scotland"}', 'Pathways EDGE - dedicated award stream for female-founded businesses within Scotland''s biggest business funding competition', 'https://www.scottishedge.com/', 'Apply online', 'https://www.scottishedge.com/scottish-edge', 'info@scottishedge.com', null, '712 awards made; £29m+ distributed', '£29m+ awarded to date', '2013 (CIC from 2014)', '4th Floor, 110 Queen Street, Glasgow G1 3BX', null, 'Jul 2026 (web research)', 'Yes', null, 'Pathways EDGE - dedicated award stream for female-founded businesses within Scotland''s biggest business funding competition', 'active'),
  ('Cartier Women''s Initiative', 'other', 'female_investors_uk', 'active', true, true, false, 'Grants: $100k / $60k / $30k + fellowship programme', '{"Impact businesses","any sector (revenue $50k-$5m","<$2m dilutive funding raised)"}', '{"Global - 9 regional awards incl. Europe (UK eligible) + thematic awards"}', 'Supports women-run and women-owned impact businesses - Regional Awards and Science & Technology Pioneer Award for women entrepreneurs', 'https://www.cartierwomensinitiative.com/', 'Apply online (annual call for applications)', 'https://www.cartierwomensinitiative.com/regional-awards', null, null, '20 years of global fellows', null, '2006', null, null, 'Jul 2026 (web research)', 'Yes', null, 'Supports women-run and women-owned impact businesses - Regional Awards and Science & Technology Pioneer Award for women entrepreneurs', 'active'),
  ('WA4STEAM', 'angel_syndicate', 'female_investors_uk', 'active', true, false, false, 'Seed capital (member-pooled angel tickets)', '{"STEAM: science","tech","engineering","arts/architecture","maths (incl. biotech","healthtech)"}', '{"International women angel community (HQ Spain","invests across Europe incl. UK-relevant deals)"}', 'A women business angels association to finance women-led STEAM projects', 'https://wa4steam.com/', 'Apply online', 'https://wa4steam.com/startups/apply-for-funding/', null, 'https://www.linkedin.com/company/wa4steam/', null, null, '2018', 'Sant Cugat del Valles, Barcelona, Spain', null, 'Jul 2026 (web research)', 'Yes', null, 'A women business angels association to finance women-led STEAM projects', 'active')
on conflict (org_name, register) do nothing;
